# Generated by Django 4.2.5 on 2023-09-25 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0004_alter_estudiante_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_nacimiento',
        ),
    ]
